"""empty message

Revision ID: 4b812bdf24c8
Revises: 679c421a4d28
Create Date: 2022-10-21 08:28:10.984970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b812bdf24c8'
down_revision = '679c421a4d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('birthdate', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mytrips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('travelling', sa.Integer(), nullable=False),
    sa.Column('with_children', sa.Boolean(), nullable=False),
    sa.Column('gender_specific', sa.Integer(), nullable=False),
    sa.Column('stay', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('partner_age', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trekking', sa.Boolean(), nullable=True),
    sa.Column('gastronomy', sa.Boolean(), nullable=True),
    sa.Column('cultural', sa.Boolean(), nullable=True),
    sa.Column('nightlife', sa.Boolean(), nullable=True),
    sa.Column('shopping', sa.Boolean(), nullable=True),
    sa.Column('trips_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trips_id'], ['mytrips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    op.drop_table('mytrips')
    op.drop_table('profile')
    # ### end Alembic commands ###
